/* ========================================
   Chalachitra — Nepali Cinema Data
   Complete history: September 14, 1951 – 2026
   ======================================== */

var CHALCHITRA = window.CHALCHITRA || {};

/* ---------- FILMS ---------- */
CHALCHITRA.films = [
  // === PRE-1964 (Early Cinema) ===
  {year:1951,title:"Satya Harishchandra",titleNe:"सत्य हरिश्चन्द्र",director:"D.B. Pariyar",actors:["D.B. Pariyar"],producer:"Bihar National Movietone",genre:"Mythological",note:"First Nepali-language film. Made in Kolkata, India. Released September 14, 1951 (Bhadra 2008 BS)."},

  // === 1960s ===
  {year:1964,title:"Aama",titleNe:"आमा",director:"Hira Singh Khatri",actors:["Shiva Shankar Manandhar","Bhuwan Chand","Chaitya Devi","Basundhara Bhusal"],producer:"Information Dept. Govt. of Nepal",genre:"Drama",note:"First film produced in Nepal. Released October 7, 1964 (Ashoj 2021 BS). Black and white. Story of a mother waiting for her son to return from military service."},
  {year:1966,title:"Maitighar",titleNe:"मैतीघर",director:"B.S. Thapa",actors:["Mala Sinha","C.P. Lohani"],producer:"Sumonanjali Films Pvt. Ltd.",genre:"Drama",music:"Jaidev",note:"First Nepali film produced under a private banner. Featured Indian actress Mala Sinha. Music by Jaidev with playback by Lata Mangeshkar, Asha Bhosle."},
  {year:1967,title:"Hijo Aaja Bholi",titleNe:"हिजो आज भोली",director:"Hira Singh Khatri",actors:["Mitra Lal Sharma","Bhuwan Chand"],producer:"Information Dept. Govt. of Nepal",genre:"Drama"},

  // === 1970s ===
  {year:1971,title:"Parivartan",titleNe:"परिवर्तन",director:"Hira Singh Khatri",producer:"Information Dept. Govt. of Nepal",genre:"Drama",note:"Change — one of the early government-produced films."},
  {year:1973,title:"Mann Ko Bandh",titleNe:"मन को बाँध",director:"Prakash Thapa",actors:["Salyan KC","Sushma Shahi"],producer:"Royal Nepal Film Corporation",genre:"Drama",music:"Nati Kaji, Shiva Shankar",note:"First film produced by Royal Nepal Film Corporation. Premiered 1973."},
  {year:1977,title:"Kumari",titleNe:"कुमारी",director:"Prem Bahadur Basnet",actors:["Biswa Basnet","Chaitya Devi"],producer:"Royal Nepal Film Corporation",genre:"Drama",note:"First Eastman color Nepali film."},
  {year:1978,title:"Paral Ko Aago",titleNe:"परालको आगो",director:"Pratap Subba",actors:["Tanka Sharma","Basundhara Bhusal","Susmita Dhakal"],producer:"Cineroma",genre:"Drama",music:"Shanti Thatal",note:"Based on story by Guru Prasad Mainali. Shanti Thatal became the first female music director in Nepali cinema."},
  {year:1979,title:"Sindoor",titleNe:"सिन्दूर",director:"Prakash Thapa",actors:["Meenaxi Anand","Biswa Basnet","Neer Shah"],producer:"Royal Nepal Film Corporation",genre:"Drama"},

  // === 1980s ===
  {year:1980,title:"Jeevan Rekha",titleNe:"जीवन रेखा",director:"Prakash Thapa",actors:["Meenaxi Anand","Shiv Shrestha"],genre:"Drama",note:"Life Line — Shiv Shrestha's debut."},
  {year:1982,title:"Badlindo Aakash",titleNe:"बदलिँदो आकाश",director:"Laxminath Sharma",actors:["Shiv Shrestha","Sushma Shahi"],producer:"Royal Nepal Film Corporation",genre:"Drama",music:"Gopal Yonzon",note:"The Changing Sky."},
  {year:1983,title:"Samjhana",titleNe:"सम्झना",director:"Shambhu Pradhan",actors:["Bhuwan KC","Trupti Totlani Narodkar","Muralidhar"],producer:"Ishwari Films",genre:"Romance",music:"Ranjit Gazmer",note:"Memories — marked the beginning of the golden era."},
  {year:1984,title:"Kanchhi",titleNe:"काँची",director:"B.S. Thapa",actors:["Shiv Shrestha","Sharmila Malla","Sushma Shahi","Mausami Malla"],producer:"Bhagawan Das Shrestha",genre:"Drama",music:"Gopal Yonzon"},
  {year:1984,title:"Adarsha Nari",titleNe:"आदर्श नारी",director:"Hem Lama",actors:["Bijay Lama","Ujwal Ghimire","Amsumala Shahi","Punam Lama"],genre:"Drama",music:"Madan Pariyar"},
  {year:1985,title:"Ke Ghar Ke Dera",titleNe:"के घर के देरा",director:"Pradeep Rimal",actors:["Puran Joshi","Sharmila Malla","Madan Krishna Shrestha","Hari Bansha Acharya","Kristi Mainali"],genre:"Comedy/Drama",note:"What's Home, What's Tenancy."},
  {year:1985,title:"Masal",titleNe:"मसल",genre:"Drama",note:"Sunil Thapa's film debut."},
  {year:1986,title:"Biswas",titleNe:"विश्वास",director:"Chetan Karki",actors:["Shiv Shrestha","Roshi Karki","Rajshri Chhetri"],producer:"Royal Nepal Film Corporation",genre:"Drama",music:"Gopal Yonzon",note:"Faith."},
  {year:1987,title:"Saino",titleNe:"साइनो",director:"Ugyen Chopel",actors:["Bhuwan KC","Trupti Totlani Narodkar","Danny Denzongpa","Raksha Mark"],producer:"Triple Jem Movies",genre:"Drama",music:"Ranjit Gazmer",note:"Relation."},
  {year:1988,title:"Sahas",titleNe:"साहस",actors:["Shiv Shrestha"],producer:"Trishakti Films",genre:"Drama",music:"Madan Pariyar",note:"Courage."},
  {year:1989,title:"Behuli",titleNe:"बेहुली",director:"Shambhu Pradhan",actors:["Sunita Khadka","Prakash Adhikari"],producer:"Ishwari Films",genre:"Drama",music:"Ranjit Gazmer",note:"The Bride."},
  {year:1989,title:"Bhagya Rekha",titleNe:"भाग्य रेखा",director:"Deepak Rayamajhi",actors:["Rabindra Khadka","Mausami Malla"],producer:"Surya Binayek Films",genre:"Drama",music:"Norbu Tshering",note:"Line of Fate."},
  {year:1989,title:"Santaan",titleNe:"सन्तान",director:"Prakash Thapa",actors:["Bhuwan KC","Arjun Jung Shahi","Ujwal Ghimire","Karishma Manandhar","Gauri Malla","Shanti Maskey","Kristi Mainali"],producer:"Om Productions / Royal Nepal Film Corporation",genre:"Drama",music:"Manohari Singh",note:"Offspring."},
  {year:1989,title:"Lahure",titleNe:"लाहुरे",director:"Tulsi Ghimire",actors:["Shrawan Ghimire","Trupti Totlani Narodkar"],producer:"Kanchanjungha Films",genre:"Drama",music:"Ranjit Gazmer",note:"The Armyman — cult classic."},

  // === 1990s ===
  {year:1990,title:"Mayalu",titleNe:"मायलु",director:"Shambhu Pradhan",actors:["Bhuwan KC","Karishma Manandhar"],producer:"Sayapatri Films",genre:"Romance",music:"Ranjit Gazmer",note:"Beloved."},
  {year:1990,title:"Cheli Beti",titleNe:"छेली बेटी",director:"Yadav Kharel",actors:["Gauri Malla","Sharmila Malla","Arjun Jung Shahi","Mithila Sharma"],producer:"Udaya Films",genre:"Drama",music:"Sambhujeet Baskota",note:"Girls/Daughters."},
  {year:1991,title:"Chino",titleNe:"चिनो",actors:["Sunil Thapa"],genre:"Drama",note:"Cult classic. Sunil Thapa's iconic role as Rate Kaila."},
  {year:1991,title:"Sampati",titleNe:"सम्पति",director:"Shambhu Pradhan",actors:["Mausami Malla","Arjun Shrestha"],producer:"Ishwari Films",genre:"Drama",music:"Ranjit Gazmer",note:"Property."},
  {year:1991,title:"Trishna",titleNe:"तृष्ना",director:"Ugyen Chopel",actors:["Bhuwan KC","Rupa Rana","Muralidhar"],producer:"Aarati Films",genre:"Romance",music:"Ranjit Gazmer",note:"Thirst."},
  {year:1993,title:"Aandhi Beri",titleNe:"आँधी बेरी",director:"Yadav Kharel",actors:["Gauri Malla","Binod Kharel"],genre:"Drama",note:"The Storm."},
  {year:1993,title:"Adhikar",titleNe:"अधिकार",director:"Prakash Thapa",actors:["Rajesh Hamal","Kristi Mainali","Mithila Sharma"],genre:"Drama",note:"The Right."},
  {year:1995,title:"Daju Bhai",titleNe:"दजु भाइ",director:"Banni Pradhan",actors:["Bhuwan KC","Shree Krishna Shrestha","Mausami Malla"],producer:"Lady Bird Films",genre:"Drama",music:"Shubh Bahadur",note:"Brothers."},
  {year:1995,title:"Sarswati",titleNe:"सरस्वती",director:"Sambhu Pradhan",actors:["Shiva Shrestha","Sunil Thapa","Gauri Malla"],genre:"Drama"},
  {year:1998,title:"Sagun",titleNe:"शगुन",actors:["Shiv Shrestha","Bipana Thapa"],genre:"Drama"},
  {year:1999,title:"Basanti",titleNe:"बसन्ती",actors:["Rajesh Hamal","Karishma Manandhar","Gauri Malla"],genre:"Drama",note:"Historical drama."},
  {year:1999,title:"Chandani",titleNe:"चन्दनी",actors:["Rajesh Hamal","Niruta Singh"],director:"Daya Ram Dahal",genre:"Romance"},
  {year:1999,title:"Nepali Babu",titleNe:"नेपाली बाबु",actors:["Dinesh Sharma","Bhuwan KC","Sunil Thapa"],director:"Yugen Chhopel",genre:"Drama"},

  // === 2000s ===
  {year:2000,title:"Basanti",titleNe:"बसन्ती",actors:["Rajesh Hamal","Karishma Manandhar","Gauri Malla"],genre:"Drama"},
  {year:2000,title:"Mukundo",titleNe:"मुकुन्डो",actors:["Gauri Malla","Mithila Sharma"],genre:"Drama/Horror",note:"Mask of Desire — screened at international festivals."},
  {year:2000,title:"Mann Mero Mandaina",titleNe:"मन मेरो मन्दैन",actors:["Dinesh Sharma","Bipana Thapa"],director:"Desh Bhakta Khanal",genre:"Drama"},
  {year:2001,title:"Darpan Chaya",titleNe:"दर्पण छायाँ",genre:"Drama/Romance",note:"Highest-grossing Nepali film at the time. Landmark of 2000s cinema."},
  {year:2001,title:"Ladai",titleNe:"लडाइ",actors:["Dinesh Sharma","Sushil Chhetri"],director:"Badri Adhikari",genre:"Action"},
  {year:2002,title:"A Mero Hajur",titleNe:"आ मेरो हजुर",actors:["Shree Krishna Shrestha","Jharana Thapa"],director:"Shiva Regmi",genre:"Romance"},
  {year:2002,title:"Maan",titleNe:"मान",actors:["Dinesh Sharma","Rejina Uprety","Uttam Pradhan","Jay Kishan Basnet"],director:"Sovit Basnet",genre:"Drama"},
  {year:2003,title:"Muna Madan",titleNe:"मुना मदन",actors:["Dayahang Rai"],director:"Gyanendra Deuja",genre:"Drama",note:"Tragic romance based on Laxmi Prasad Devkota's epic poem. Highest-rated Nepali film."},
  {year:2003,title:"Je Bho Ramrai Bho",titleNe:"जे भो रम्रै भो",actors:["Hari Bansha Acharya","Laxmi Giri","Rajesh Hamal","Jal Shah","Mithila Sharma","Madan Krishna Shrestha","Sunil Thapa"],director:"Hari Bansha Acharya",genre:"Comedy/Drama",note:"Landmark comedy."},
  {year:2003,title:"Jetho Kancha",titleNe:"जेठो काँचा",actors:["Shiv Shrestha","Rajesh Hamal","Jal Shah"],director:"Dayaram Dahal",genre:"Drama"},
  {year:2004,title:"Numafung",titleNe:"नुमाफुङ",actors:["Khadka Raj Nepali"],director:"Nabin Subba",genre:"Drama",note:"First Limbu-language film. Screened at international festivals."},
  {year:2004,title:"Hami Teen Bhai",titleNe:"हामी तीन भाइ",genre:"Thriller/Drama/Romance",note:"Highly rated 2000s film."},
  {year:2005,title:"Basain",titleNe:"बसाइँ",director:"Subash Gajurel",genre:"Drama",note:"Dwell — 90-minute drama."},
  {year:2006,title:"Duniya",titleNe:"दुनिया",actors:["Dinesh Sharma","Nikhil Upreti"],director:"Shiva Regmi",genre:"Drama"},
  {year:2007,title:"Dewar Babu",titleNe:"देवर बाबु",genre:"Drama",note:"Popular 2000s film."},
  {year:2008,title:"Kagbeni",titleNe:"कागबेनी",director:"Bhusan Dahal",actors:["Deepraj Rai","Karma Wangel"],genre:"Drama/Thriller",note:"First digital Nepali film. Shot in Kagbeni, Mustang. Released January 10, 2008."},
  {year:2008,title:"Sano Sansar",titleNe:"सानो संसार",director:"Alok Nembang",actors:["Mahesh Shakya","Jivan Luintel","Namrata Shrestha"],genre:"Comedy/Romance",note:"Small World — quest entertainment."},
  {year:2008,title:"Sandesh",titleNe:"सन्देश",actors:["Rejina Uprety","Biraj Bhatta","Sushil Chhetri","Rekha Thapa","Sovita Simkhada"],director:"Pramod Bhandari",genre:"Drama"},
  {year:2008,title:"Karnabir",titleNe:"कर्णवीर",actors:["Rajesh Hamal","Rejina Uprety","Rekha Thapa","Jaikishan Basnet"],director:"Shovit Basnet",genre:"Action"},
  {year:2009,title:"Deewanapan",titleNe:"दीवानापन",actors:["Dinesh Sharma","Arunima Lamsal","Raj Ballav Koirala"],director:"Krishna Chapagain",genre:"Drama"},
  {year:2009,title:"Izzatdar",titleNe:"इज्जतदार",actors:["Dinesh Sharma","Rajesh Hamal","Biraj Bhatta","Arjun Karki"],director:"Krishna Chapagain",genre:"Action"},
  {year:2009,title:"Silsila",titleNe:"सिलसिला",genre:"Thriller/Drama/Action",note:"Popular 2000s film."},
  {year:2009,title:"Mission Paisa",titleNe:"मिशन पैसा",genre:"Crime",note:"Mission Money."},

  // === 2010s ===
  {year:2010,title:"Dasdhunga",titleNe:"दशधुङ्गा",genre:"Drama",note:"Historical film."},
  {year:2011,title:"Gorkha Paltan",titleNe:"गोर्खा पाल्टन",actors:["Sunil Thapa"],genre:"Action/Drama"},
  {year:2012,title:"Loot",titleNe:"लूट",director:"Nischal Basnet",actors:["Saugat Malla","Dayahang Rai","Bipin Karki","Reecha Sharma"],genre:"Crime/Drama",note:"Turning point for Nepali cinema. Brought audiences back to theatres. Highest-grossing at the time."},
  {year:2012,title:"Highway",titleNe:"हाइवे",director:"Deepak Rauniyar",genre:"Drama",note:"First Nepali film screened at Berlin International Film Festival."},
  {year:2013,title:"Kaha Bhetiyela",titleNe:"कहाँ भेटियेला",genre:"Romance/Drama"},
  {year:2013,title:"Notebook",titleNe:"नोटबुक",genre:"Drama",note:"Popular 2010s film."},
  {year:2014,title:"Talakjung vs Tulke",titleNe:"तलकजंग भर्सेस तुल्के",director:"Nischal Basnet",genre:"Drama"},
  {year:2015,title:"Kalo Pothi",titleNe:"कालो पोथी",director:"Min Bahadur Bham",actors:["Khadka Raj Nepali","Sukraj Rokaya","Jit Bahadur Malla","Benisha Hamal Khadka"],genre:"Drama",note:"The Black Hen. Won Fedeora Award at Venice Critics' Week 2015."},
  {year:2016,title:"White Sun",titleNe:"सेतो सूर्य",director:"Deepak Rauniyar",actors:["Dayahang Rai","Rabindra Singh Baniya"],genre:"Drama",note:"Won Interfilm Award at Venice. Nepal's Oscar submission."},
  {year:2016,title:"Bijuli Machine",titleNe:"बिजुली मेसिन",director:"Navin Awal",genre:"Sci-Fi/Comedy",note:"Nepal's first science-fiction film."},
  {year:2017,title:"Loot 2",titleNe:"लूट २",director:"Nischal Basnet",actors:["Saugat Malla","Dayahang Rai","Bipin Karki"],genre:"Crime/Drama",note:"Sequel to the 2012 blockbuster."},
  {year:2017,title:"Dui Rupaiyan",titleNe:"दुई रुपैयाँ",director:"Asim Shah",actors:["Nischal Basnet"],genre:"Drama"},
  {year:2018,title:"Changa Chet",titleNe:"चङ्गा चेत",genre:"Drama",note:"Special appearance by Nischal Basnet."},
  {year:2018,title:"Pashupati Prasad",titleNe:"पशुपति प्रसाद",genre:"Drama/Comedy",note:"Critically acclaimed."},
  {year:2019,title:"Bulbul",titleNe:"बुलबुल",director:"Binod Paudel",genre:"Drama",note:"Nepal's official Academy Awards submission."},
  {year:2019,title:"Captain",titleNe:"क्याप्टेन",genre:"Drama",note:"Popular 2010s film."},
  {year:2019,title:"Loot 3 (announced)",genre:"Crime/Drama",note:"Franchise continuation."},

  // === 2020s ===
  {year:2020,title:"Nalapani",titleNe:"नलपानी",genre:"History/Drama",note:"Historical war film."},
  {year:2021,title:"Pashupati Prasad 2",titleNe:"पशुपति प्रसाद २",genre:"Drama/Comedy"},
  {year:2022,title:"Kabaddi 4: The Final Match",titleNe:"कबड्डी ४",genre:"Drama/Sport",note:"Final installment of the Kabaddi franchise."},
  {year:2023,title:"Nango Gaun",titleNe:"नाङ्गो गाउँ",genre:"Drama",note:"Highest-rated recent Nepali film. 2h 31min."},
  {year:2023,title:"Fulbari",titleNe:"फूलबारी",genre:"Drama",note:"2h 11min."},
  {year:2024,title:"Shambhala",titleNe:"शम्भाला",director:"Min Bahadur Bham",genre:"Drama",note:"First Nepali feature in Berlinale Competition."},
  {year:2024,title:"Pooja, sir",titleNe:"पूजा, सर",director:"Deepak Rauniyar",genre:"Drama",note:"Won Best Actress at Venice Orizzonti."},
  {year:2024,title:"Gurkha Warrior",titleNe:"गोर्खा वारियर",genre:"Action/Drama",note:"1h 55min."},
  {year:2025,title:"Dimag Kharab",titleNe:"दिमाग खराब",director:"Nischal Basnet",genre:"Drama"},
  {year:2026,title:"Parbati",titleNe:"पार्वती",genre:"Social",note:"2026 release."},
  {year:2026,title:"Masterni",titleNe:"मास्टरनी",genre:"Crime",note:"123 minutes."},
  {year:2026,title:"Lajjawati",titleNe:"लज्जावती",genre:"Drama",note:"2h 15m."},
  {year:2026,title:"Kamala Miss",titleNe:"कमला मिस",genre:"Drama"},
  {year:2026,title:"Halee",titleNe:"हली",genre:"Drama"},
  {year:2026,title:"Gauthali",titleNe:"गौथली",genre:"Drama",note:"140 minutes."},
  {year:2026,title:"Bhagdaud",titleNe:"भागदौड",genre:"Social"},
  {year:2026,title:"Jaand",titleNe:"जाँद",genre:"Drama"},
  {year:2026,title:"I Am Jit Bahadur",titleNe:"आई एम जित बहादुर",genre:"Drama",note:"2h 13m."},
  {year:2026,title:"Roll No. 1",titleNe:"रोल नं. १",genre:"Drama",note:"2h 32m."},
  {year:2026,title:"Kumbha",titleNe:"कुम्भ",genre:"Action",note:"2h 0m."},
  {year:2026,title:"Kaji",titleNe:"काजी",genre:"Drama",note:"2h 26m."},
  {year:2026,title:"Mitajyu",titleNe:"मितज्यु",genre:"Drama",note:"2h 16m."},
  {year:2026,title:"Life Dyamage",titleNe:"लाइफ ड्यामेज",genre:"Comedy",note:"1h 57m."},
  {year:2026,title:"Ek Mutthi Badal",titleNe:"एक मुठ्ठी बादल",genre:"Drama",note:"1h 57m."},
  {year:2026,title:"Guru Aama",titleNe:"गुरु आमा",genre:"Drama",note:"2h 10m."},
  {year:2026,title:"Lalibazar",titleNe:"लालीबजार",genre:"Drama",note:"2h 17m."},
  {year:2026,title:"Malati Mangale",titleNe:"मालती मंगले",genre:"Drama",note:"2h 38m."},
  {year:2026,title:"Paral Ko Aago",titleNe:"परालको आगो",genre:"Drama",note:"2h 15m — remake of the 1978 classic."},
  {year:2026,title:"Pahad",titleNe:"पहाड",genre:"Drama",note:"2h 45m — directed by Tulsi Ghimire. Sunil Thapa's final film."},
  {year:2026,title:"Ram Naam Satya",titleNe:"राम नाम सत्य",genre:"Action",note:"2h 37m."},
  {year:2026,title:"Hami Teen Bhai",titleNe:"हामी तीन भाइ",genre:"Drama",note:"2h 17m."},
  {year:2026,title:"Laalimaa",titleNe:"लालिमा",genre:"Drama",note:"1h 57m."},
  {year:2026,title:"Prawasi Jiwan",titleNe:"प्रवासी जीवन",genre:"Drama",note:"1h 55m."},
  {year:2026,title:"Eklo",titleNe:"एक्लो",genre:"Drama",note:"Sunil Thapa's last released film."},
];

/* ---------- PEOPLE ---------- */
CHALCHITRA.people = [
  // === PIONEERS (1950s-1970s) ===
  {name:"D.B. Pariyar",nameNe:"डी.बी. परियार",role:"Producer/Director",born:"—",died:"—",note:"Produced Satya Harishchandra (1951), the first Nepali-language film."},
  {name:"Hira Singh Khatri",nameNe:"हीरा सिंह खत्री",role:"Director",born:"—",died:"—",note:"Directed Aama (1964), the first film produced in Nepal."},
  {name:"Shiva Shankar Manandhar",nameNe:"शिवशंकर मानन्धर",role:"Actor",born:"—",died:"—",note:"Lead actor in Aama (1964). One of the first actors in Nepali cinema."},
  {name:"Bhuwan Chand",nameNe:"भुवन चन्द",role:"Actor",born:"—",died:"—",note:"Lead actor in Aama (1964). Pioneer of Nepali cinema."},
  {name:"Chaitya Devi",nameNe:"चैत्या देवी",role:"Actress",born:"—",died:"—",note:"Lead actress in Aama (1964). One of the first actresses in Nepali cinema."},
  {name:"Basundhara Bhusal",nameNe:"बसुन्धरा भुसाल",role:"Actress",born:"—",died:"—",note:"Acted in Aama (1964) and Paral Ko Aago (1978). Pioneer actress."},
  {name:"Shanti Thatal",nameNe:"शान्ति थापा",role:"Music Director",born:"—",died:"—",note:"First female music director in Nepali cinema. Composed music for Paral Ko Aago (1978)."},

  // === GOLDEN ERA (1980s-1990s) ===
  {name:"Bhuwan K.C.",nameNe:"भुवन के.सी.",role:"Actor",born:"—",died:"—",note:"One of the biggest stars of the golden era. Known as the 'golden couple' with Tripti Nadakar."},
  {name:"Tripti Nadakar",nameNe:"त्रिप्ति नदाकर",role:"Actress",born:"—",died:"—",note:"'Golden couple' with Bhuwan K.C. Dominated 1980s-90s Nepali cinema."},
  {name:"Rajesh Hamal",nameNe:"राजेश हमाल",role:"Actor",born:"—",died:"—",note:"One of the most prolific actors in Nepali cinema history. Starred in hundreds of films."},
  {name:"Karishma Manandhar",nameNe:"करिश्मा मानन्धर",role:"Actress",born:"—",died:"—",note:"Leading actress of the 1980s-90s. Worked in over 100 films."},
  {name:"Shiv Shrestha",nameNe:"शिव श्रेष्ठ",role:"Actor",born:"—",died:"—",note:"Debut in Jeevan Rekha (1980). One of the most respected actors in Nepali cinema."},
  {name:"Gauri Malla",nameNe:"गौरी मल्ल",role:"Actress",born:"—",died:"—",note:"Versatile actress active from the 1980s. Acted in over 80 films."},
  {name:"Saroj Khanal",nameNe:"सरोज खनाल",role:"Actor/Director",born:"—",died:"—",note:"Actor and director. Active from the 1980s."},
  {name:"Sunil Thapa",nameNe:"सुनील थापा",role:"Actor",born:"May 19, 1957",died:"February 7, 2026",note:"Died age 68 in Kathmandu. Over 300 films. Iconic villain in Chino (1991). Appeared in Mary Kom (2014) and The Family Man S3. Chairperson of Everest Film Academy. Cardiac arrest."},
  {name:"Tulsi Ghimire",nameNe:"तुलसी घिमिरे",role:"Director",born:"—",died:"—",note:"Directed Lahure (1989) and many other classics. One of Nepal's most celebrated directors."},
  {name:"Nischal Basnet",nameNe:"निस्चल बस्नेत",role:"Director/Actor",born:"—",died:"—",note:"Directed Loot (2012), Talakjung vs Tulke (2014), Loot 2 (2017). Revolutionized modern Nepali cinema."},
  {name:"Deepak Rauniyar",nameNe:"दीपक रौनियार",role:"Director",born:"August 29, 1978",died:"—",note:"Directed Highway (2012), White Sun (2016), Pooja sir (2024). Venice and Berlin alumnus."},
  {name:"Min Bahadur Bham",nameNe:"मिन बहादुर भम",role:"Director",born:"—",died:"—",note:"Directed Kalo Pothi (2015), Shambhala (2024). Venice Critics' Week winner. Berlinale Competition."},
  {name:"Bhusan Dahal",nameNe:"भुषण दाहाल",role:"Director",born:"—",died:"—",note:"Directed Kagbeni (2008), the first digital Nepali film."},
  {name:"Saugat Malla",nameNe:"सौगात मल्ल",role:"Actor",born:"—",died:"—",note:"Breakout role in Loot (2012) as Haku Kale. Cult following."},
  {name:"Dayahang Rai",nameNe:"दयाहाङ राई",role:"Actor",born:"—",died:"—",note:"Versatile actor. Starred in Muna Madan, Loot, White Sun, and many others."},
  {name:"Bipin Karki",nameNe:"बिपिन कार्की",role:"Actor",born:"—",died:"—",note:"Known for Loot and Loot 2. Popular comedic and dramatic actor."},
  {name:"Namrata Shrestha",nameNe:"नम्रता श्रेष्ठ",role:"Actress",born:"—",died:"—",note:"Popular actress from the late 2000s onward."},
  {name:"Rekha Thapa",nameNe:"रेखा थापा",role:"Actress/Director",born:"—",died:"—",note:"One of the most popular actresses of the 2000s-2010s."},
  {name:"Nikhil Upreti",nameNe:"निखिल उप्रेती",role:"Actor",born:"—",died:"—",note:"Action star of the 2000s."},
  {name:"Biraj Bhatta",nameNe:"बिरज भट्ट",role:"Actor",born:"—",died:"—",note:"Action star of the 2000s."},
  {name:"Rejina Uprety",nameNe:"रेजिना उप्रेती",role:"Actress",born:"—",died:"—",note:"Popular actress of the 2000s."},
  {name:"Priyanka Karki",nameNe:"प्रियंका कार्की",role:"Actress",born:"—",died:"—",note:"One of the most popular contemporary actresses."},
  {name:"Asha Magrati",nameNe:"आशा मगराती",role:"Actress/Producer",born:"—",died:"—",note:"Won Best Actress at Venice Orizzonti for Pooja, sir (2024)."},

  // === RECENT DEATHS ===
  {name:"Sunil Thapa",nameNe:"सुनील थापा",role:"Actor",born:"May 19, 1957",died:"February 7, 2026",note:"Died age 68 in Kathmandu. Over 300 films. Cardiac arrest. Tributes from Priyanka Chopra, Manoj Bajpayee."},
  {name:"Subhadra Adhikari",nameNe:"सुभद्रा अधिकारी",role:"Actress",born:"1946",died:"August 17, 2019",note:"Veteran actress. Acted in Basanti, Basudev, Batomuni Ko Phool, Chino. Died at 73 from respiratory problems."},
  {name:"Saruk Tamrakar",nameNe:"सारुक ताम्रकार",role:"Actor",born:"~1992",died:"July 7, 2023",note:"Actor (Hashtag Maya, Meri Mamu, Rani). Found dead at age 31 in Kathmandu."},
  {name:"Shree Krishna Shrestha",nameNe:"श्रीकृष्ण श्रेष्ठ",role:"Actor",born:"—",died:"2014",note:"Popular actor of the 1990s-2000s. Acted in Daju Bhai, Ram Balram, and many others."},

  // === ADDITIONAL NOTABLE PEOPLE ===
  {name:"Madan Krishna Shrestha",nameNe:"मदन कृष्ण श्रेष्ठ",role:"Actor/Comedian",born:"—",died:"—",note:"One half of the iconic comedy duo with Hari Bansha Acharya."},
  {name:"Hari Bansha Acharya",nameNe:"हरि बंश आचार्य",role:"Actor/Comedian",born:"—",died:"—",note:"One half of the iconic comedy duo with Madan Krishna Shrestha."},
  {name:"Kristi Mainali",nameNe:"क्रिस्टी मैनाली",role:"Actress",born:"—",died:"—",note:"Active from the 1980s. Acted in Ke Ghar Ke Dera, Santaan, and others."},
  {name:"Mausami Malla",nameNe:"मौसमी मल्ल",role:"Actress",born:"—",died:"—",note:"Active from the 1980s. Acted in Bhagya Rekha, Daju Bhai, Sampati, and others."},
  {name:"Mithila Sharma",nameNe:"मिथिला शर्मा",role:"Actress",born:"—",died:"—",note:"Versatile actress. Acted in Adhikar, Basanti, Je Bho Ramrai Bho, and many others."},
  {name:"Jal Shah",nameNe:"जल शाह",role:"Actress",born:"—",died:"—",note:"Popular actress of the 1990s-2000s."},
  {name:"Niruta Singh",nameNe:"निरुता सिंह",role:"Actress",born:"—",died:"—",note:"Popular actress of the late 1990s-2000s."},
  {name:"Dinesh Sharma",nameNe:"दिनेश शर्मा",role:"Actor",born:"—",died:"—",note:"Prolific actor of the 2000s."},
  {name:"Arunima Lamsal",nameNe:"अरुणिमा लम्साल",role:"Actress",born:"—",died:"—",note:"Actress of the late 2000s."},
  {name:"Raj Ballav Koirala",nameNe:"राजबल्लव कोइराला",role:"Actor",born:"—",died:"—",note:"Actor of the late 2000s-2010s."},
  {name:"Wilson Bikram Rai",nameNe:"विल्सन बिक्रम राई",role:"Actor",born:"—",died:"—",note:"Known as 'Takme Budha'. Character actor."},
  {name:"Neer Shah",nameNe:"नीर शाह",role:"Actor/Director",born:"—",died:"—",note:"Veteran actor and director."},
  {name:"Anup Baral",nameNe:"अनुप बराल",role:"Actor",born:"—",died:"—",note:"Versatile character actor."},
  {name:"Sitaram Kattel",nameNe:"सीताराम कट्टेल",role:"Actor/Comedian",born:"—",died:"—",note:"Popular comedian known as 'Dhurmus'."},
  {name:"Kedar Ghimire",nameNe:"केदार घिमिरे",role:"Actor/Comedian",born:"—",died:"—",note:"Popular comedian known as 'Suntali' partner."},
  {name:"Deepak Raj Giri",nameNe:"दीपक राज गिरी",role:"Actor/Producer",born:"—",died:"—",note:"Actor and producer. Co-founder of Tito Satya."},
  {name:"Jharana Thapa",nameNe:"झरना थापा",role:"Actress/Director",born:"—",died:"—",note:"Actress turned director."},
  {name:"Manisha Koirala",nameNe:"मनिषा कोइराला",role:"Actress",born:"August 16, 1970",died:"—",note:"Nepali-born Bollywood actress. International career."},
  {name:"Bipana Thapa",nameNe:"बिपना थापा",role:"Actress",born:"—",died:"—",note:"Actress of the late 1990s-2000s."},
  {name:"Prakash Thapa",nameNe:"प्रकाश थापा",role:"Director",born:"—",died:"—",note:"Directed Mann Ko Bandh, Sindoor, Santaan, and others."},
  {name:"Shambhu Pradhan",nameNe:"शम्भु प्रधान",role:"Director",born:"—",died:"—",note:"Directed Samjhana, Mayalu, Sarswati, and others."},
  {name:"Yadav Kharel",nameNe:"यादव खरेल",role:"Director",born:"—",died:"—",note:"Directed Cheli Beti, Aandhi Beri, and others."},
  {name:"Deepak Rayamajhi",nameNe:"दीपक रायमाझी",role:"Director",born:"—",died:"—",note:"Directed Bhagya Rekha and others."},
  {name:"Ugyen Chopel",nameNe:"उग्येन चोपेल",role:"Director",born:"—",died:"—",note:"Directed Saino, Trishna, and others."},
  {name:"Alok Nembang",nameNe:"अलोक नेम्बाङ",role:"Director",born:"—",died:"—",note:"Directed Sano Sansar. Music video director."},
  {name:"Shiva Regmi",nameNe:"शिव रेग्मी",role:"Director",born:"—",died:"—",note:"Directed A Mero Hajur, Duniya, and others."},
];

/* ---------- KEY EVENTS / MILESTONES ---------- */
CHALCHITRA.events = [
  {year:1951,date:"September 14, 1951",event:"Satya Harishchandra released",note:"First Nepali-language film. Made in Kolkata, India by D.B. Pariyar. Bhadra 2008 BS."},
  {year:1964,date:"October 7, 1964",event:"Aama released",note:"First film produced in Nepal. Directed by Hira Singh Khatri. Ashoj 2021 BS."},
  {year:1966,event:"Maitighar released",note:"First Nepali film produced under a private banner (Sumonanjali Films)."},
  {year:1971,event:"Royal Nepal Film Corporation established",note:"State film body created by Nepal government."},
  {year:1973,event:"Mann Ko Bandh premiered",note:"First film produced by Royal Nepal Film Corporation."},
  {year:1977,event:"Kumari released",note:"First Eastman color Nepali film."},
  {year:1978,event:"Paral Ko Aago released",note:"Shanti Thatal became the first female music director in Nepali cinema."},
  {year:1980,event:"Golden era begins",note:"More films being made, better audience acceptance. Bhuwan K.C. and Tripti Nadakar become the 'golden couple'."},
  {year:1984,event:"Kanchhi and Badlindo Aakash released",note:"Start of a prolific period for Nepali cinema."},
  {year:1989,event:"Lahure released",note:"Tulsi Ghimire's cult classic. One of the most beloved Nepali films."},
  {year:1990,event:"Industry rapid growth",note:"Unprecedented growth in productions. Within three years, 140 films made. Cinemas increased to 300+."},
  {year:1991,event:"Chino released",note:"Sunil Thapa's iconic villain role as Rate Kaila. Became a cult classic."},
  {year:1996,event:"Maoist insurgency begins",note:"Nepali film industry enters a slump. Very few films produced."},
  {year:2001,event:"Darpan Chaya released",note:"Highest-grossing Nepali film at the time. Landmark of 2000s cinema."},
  {year:2006,event:"Conflict ends, industry revives",note:"Maoists enter mainstream politics. Film industry begins recovery."},
  {year:2008,event:"Kagbeni released",note:"First digital Nepali film. Shot in Kagbeni, Mustang."},
  {year:2012,event:"Loot released",note:"Turning point for modern Nepali cinema. Brought audiences back to theatres. Directed by Nischal Basnet."},
  {year:2012,event:"Highway screened at Berlin",note:"First Nepali film screened at Berlin International Film Festival."},
  {year:2015,event:"Kalo Pothi wins at Venice",note:"Min Bahadur Bham's debut wins Fedeora Award at Venice Critics' Week."},
  {year:2016,event:"White Sun wins at Venice",note:"Deepak Rauniyar's film wins Interfilm Award. Nepal's Oscar submission."},
  {year:2016,event:"Bijuli Machine released",note:"Nepal's first science-fiction film."},
  {year:2024,event:"Shambhala at Berlinale Competition",note:"First Nepali feature selected for Competition at Berlin International Film Festival."},
  {year:2024,event:"Pooja sir wins at Venice",note:"Asha Magrati wins Best Actress at Venice Orizzonti."},
  {year:2026,date:"February 7, 2026",event:"Sunil Thapa passes away",note:"Veteran actor dies at 68 in Kathmandu. Over 300 films. Tributes from Priyanka Chopra, Manoj Bajpayee."},
];

/* ---------- DEATHS / IN MEMORIAM ---------- */
CHALCHITRA.inMemoriam = [
  {name:"Sunil Thapa",year:2026,age:68,cause:"Cardiac arrest",note:"Veteran actor. 300+ films. Mary Kom, The Family Man S3, Chino."},
  {name:"Subhadra Adhikari",year:2019,age:73,cause:"Respiratory problems",note:"Veteran actress. Basanti, Basudev, Chino."},
  {name:"Saruk Tamrakar",year:2023,age:31,cause:"Found dead",note:"Actor. Hashtag Maya, Meri Mamu, Rani."},
  {name:"Shree Krishna Shrestha",year:2014,age:"—",cause:"—",note:"Popular actor. Daju Bhai, Ram Balram."},
];

/* ---------- DECADES ---------- */
CHALCHITRA.decades = [
  {id:"1950s",label:"1950s",sublabel:"The Beginning",yearStart:1951,yearEnd:1959,note:"Satya Harishchandra (1951) — the first Nepali-language film, made in Kolkata."},
  {id:"1960s",label:"1960s",sublabel:"First Productions",yearStart:1960,yearEnd:1969,note:"Aama (1964) — first film produced in Nepal. Maitighar (1966) — first private banner film."},
  {id:"1970s",label:"1970s",sublabel:"State Cinema",yearStart:1970,yearEnd:1979,note:"Royal Nepal Film Corporation established (1971). First color film Kumari (1977)."},
  {id:"1980s",label:"1980s",sublabel:"Golden Era",yearStart:1980,yearEnd:1989,note:"Bhuwan K.C. and Tripti Nadakar as the 'golden couple'. Lahure, Kanchhi, Saino."},
  {id:"1990s",label:"1990s",sublabel:"Growth & Conflict",yearStart:1990,yearEnd:1999,note:"Rapid growth (140 films in 3 years). Then Maoist insurgency caused a slump."},
  {id:"2000s",label:"2000s",sublabel:"Revival",yearStart:2000,yearEnd:2009,note:"Darpan Chaya. Kagbeni (first digital). Industry recovering from conflict."},
  {id:"2010s",label:"2010s",sublabel:"New Wave",yearStart:2010,yearEnd:2019,note:"Loot (2012) revolutionized cinema. International festival recognition begins."},
  {id:"2020s",label:"2020s",sublabel:"Global Recognition",yearStart:2020,yearEnd:2029,note:"Shambhala at Berlinale Competition. Pooja sir at Venice. Sunil Thapa passes away."},
];
